version: "3"

services:
  nginx:
    image: nginx
    container_name: 'kubrik_nginx'
    ports:
      - ${PORT}:80
    volumes:
      - ./frontend/dist:/var/www/public
      - ./etc/nginx/site.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend

  backend:
    image: node
    container_name: 'kubrik_backend'
    ports:
      - ${BACKEND_PORT}:3000
      - ${BACKEND_DEBUG_PORT}:9229
    depends_on:
      - mongo
    volumes:
      - ./backend:/var/www
    working_dir: /var/www
    environment:
      - NODE_ENV=development
      - MONGO_HOST=kubrik_mongo
      - MONGO_DB=kubrik
      - BOT_TOKEN=${BOT_TOKEN}
      - CHAT_ID=${CHAT_ID}
    command: npm run debug

  bot:
    image: node
    container_name: 'kubrik_bot'
    ports:
      - ${BOT_DEBUG_PORT}:9229
    depends_on:
      - mongo
    volumes:
      - ./backend:/var/www
    working_dir: /var/www
    environment:
      - NODE_ENV=development
      - MONGO_HOST=kubrik_mongo
      - MONGO_DB=kubrik
      - BOT_TOKEN=${BOT_TOKEN}
      - CHAT_ID=${CHAT_ID}
    command: npm run bot_debug

  mongo:
    image: mongo
    container_name: 'kubrik_mongo'
    volumes:
      - ./etc/database:/data/db
    ports:
      - ${MONGO_PORT}:27017