version: "3"

services:
  nginx:
    image: nginx
    container_name: 'jobbo_nginx'
    ports:
      - ${PORT}:80
    volumes:
      - ./frontend/dist:/var/www/public
      - ./etc/nginx/site.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend

  backend:
    image: node
    container_name: 'jobbo_backend'
    ports:
      - 3000:3000
    depends_on:
      - mongo
    volumes:
      - ./backend:/var/www
    working_dir: /var/www
    environment:
      - NODE_ENV=development
      - MONGO_HOST=jobbo_mongo
      - MONGO_DB=jobbo
    command: npm run start

  mongo:
    image: mongo
    container_name: 'jobbo_mongo'
    volumes:
      - ./etc/database:/data/db
    ports:
      - ${MONGO_PORT}:27017